language: generic
services:
  - docker
jobs:
  include:
    - stage: tests
      before_script:
        - docker build -t ign0ramus/multi-docker-container-test-app-frontend -f ./frontend/Dockerfile.dev ./frontend
      script:
        - docker run -e CI=true ign0ramus/multi-docker-container-test-app-frontend npm run test

    - stage: build & commit images
      script:
        - docker-compose build
      after_success:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
        - docker-compose push

    - stage: deploy
      script: skip
      deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker-container-test-app
        env: MultiDockerContainerTestApp-env
        bucket: elasticbeanstalk-us-east-2-737637823476
        bucket_path: docker-multi
        access_key_id: $AWS_SECRET_KEY
        secret_access_key: $AWS_ACCESS_KEY
        on:
          branch: master
