language: generic
services:
  - docker
jobs:
  include:
    - stage: tests
      before_script:
        - docker build -t ign0ramus/multi-docker-container-test-app-frontend -f ./frontend/Dockerfile.dev ./frontend
      script:
        - docker run -e CI=true ign0ramus/multi-docker-container-test-app-frontend npm run test

    - stage: build & commit images
      script:
        - docker-compose build
      after_success:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
        - docker-compose push
