version: '3'

services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    redis:
        image: 'redis:latest'

    api:
        build: 
            context: ./server
            dockerfile: Dockerfile
        image: ign0ramus/multi-docker-container-test-app_api:${VERSION_TAG:-latest}
        volumes: 
            - /app/node_modules
            - ./server:/app
        depends_on: 
            - postgres
            - redis
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=${PGUSER}
            - PGHOST=postgres
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=5432
            
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        image: ign0ramus/multi-docker-container-test-app_worker:${VERSION_TAG:-latest}
        volumes:
            - /app/node_modules
            - ./worker:/app
        depends_on: 
            - redis
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    frontend:
        stdin_open: true
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: ign0ramus/multi-docker-container-test-app_frontend:${VERSION_TAG:-latest}
        volumes:  
            - /app/node_modules
            - ./frontend:/app

        